# Generated by Django 6.0.4 on 2026-04-16 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('Num_Acc', models.BigIntegerField(primary_key=True, serialize=False)),
                ('jour', models.CharField(blank=True, max_length=255, null=True)),
                ('mois', models.CharField(blank=True, max_length=255, null=True)),
                ('an', models.CharField(blank=True, max_length=255, null=True)),
                ('hrmn', models.CharField(blank=True, max_length=10, null=True)),
                ('lum', models.CharField(blank=True, max_length=255, null=True)),
                ('dep', models.CharField(blank=True, max_length=3, null=True)),
                ('com', models.CharField(blank=True, max_length=255, null=True)),
                ('agg', models.CharField(blank=True, max_length=255, null=True)),
                ('intersection_col', models.CharField(blank=True, db_column='int', max_length=255, null=True)),
                ('atm', models.CharField(blank=True, max_length=255, null=True)),
                ('col', models.CharField(blank=True, max_length=255, null=True)),
                ('adr', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catr', models.CharField(blank=True, max_length=255, null=True)),
                ('voie', models.CharField(blank=True, max_length=255, null=True)),
                ('V1', models.CharField(blank=True, max_length=255, null=True)),
                ('V2', models.CharField(blank=True, max_length=10, null=True)),
                ('circ', models.CharField(blank=True, max_length=255, null=True)),
                ('nbv', models.CharField(blank=True, max_length=10, null=True)),
                ('vosp', models.CharField(blank=True, max_length=255, null=True)),
                ('prof', models.CharField(blank=True, max_length=255, null=True)),
                ('pr', models.CharField(blank=True, max_length=20, null=True)),
                ('pr1', models.CharField(blank=True, max_length=20, null=True)),
                ('plan', models.CharField(blank=True, max_length=255, null=True)),
                ('lartpc', models.CharField(blank=True, max_length=255, null=True)),
                ('larrout', models.CharField(blank=True, max_length=255, null=True)),
                ('surf', models.CharField(blank=True, max_length=255, null=True)),
                ('infra', models.CharField(blank=True, max_length=255, null=True)),
                ('situ', models.CharField(blank=True, max_length=255, null=True)),
                ('vma', models.IntegerField(blank=True, null=True)),
                ('Num_Acc', models.ForeignKey(db_column='Num_Acc', on_delete=django.db.models.deletion.CASCADE, related_name='lieux', to='api.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num_veh', models.CharField(blank=True, max_length=10, null=True)),
                ('senc', models.CharField(blank=True, max_length=255, null=True)),
                ('catv', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('obsm', models.CharField(blank=True, max_length=255, null=True)),
                ('choc', models.CharField(blank=True, max_length=255, null=True)),
                ('manv', models.CharField(blank=True, max_length=255, null=True)),
                ('motor', models.CharField(blank=True, max_length=255, null=True)),
                ('occutc', models.CharField(blank=True, max_length=255, null=True)),
                ('Num_Acc', models.ForeignKey(db_column='Num_Acc', on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='api.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Usager',
            fields=[
                ('id_usager', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num_veh', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('catu', models.CharField(blank=True, max_length=255, null=True)),
                ('grav', models.CharField(blank=True, max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, max_length=255, null=True)),
                ('an_nais', models.CharField(blank=True, max_length=255, null=True)),
                ('trajet', models.CharField(blank=True, max_length=255, null=True)),
                ('secu1', models.CharField(blank=True, max_length=255, null=True)),
                ('secu2', models.CharField(blank=True, max_length=255, null=True)),
                ('secu3', models.CharField(blank=True, max_length=255, null=True)),
                ('locp', models.CharField(blank=True, max_length=255, null=True)),
                ('actp', models.CharField(blank=True, max_length=10, null=True)),
                ('etatp', models.CharField(blank=True, max_length=255, null=True)),
                ('Num_Acc', models.ForeignKey(db_column='Num_Acc', on_delete=django.db.models.deletion.CASCADE, related_name='usagers', to='api.accident')),
                ('id_vehicule', models.ForeignKey(db_column='id_vehicule', on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='api.vehicule')),
            ],
        ),
    ]
