# Generated by Django 5.1.4 on 2026-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lieu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDepartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('kmeans', 'K-Means'), ('bisecting', 'Bisecting K-Means'), ('gmm', 'Gaussian Mixture Model')], db_index=True, max_length=20)),
                ('departement', models.CharField(db_index=True, max_length=3)),
                ('cluster_number', models.IntegerField()),
                ('pct_indemne', models.FloatField(default=0.0)),
                ('pct_blesse_leger', models.FloatField(default=0.0)),
                ('pct_blesse_grave', models.FloatField(default=0.0)),
                ('pct_tue', models.FloatField(default=0.0)),
                ('recommandation', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('model_name', 'departement', 'cluster_number')},
            },
        ),
    ]
